on:
  push:
    branches:
      - itowns_potree
  pull_request:
    branches:
      - itowns_potree
  workflow_dispatch: {}

name: integration
env:
  CI: true

jobs:
  tests:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    # install package
    # TODO: add cache npm to speed up installing
    - name: Install packages
      run: npm ci

    # Build bundle
    - name: Build bundle
      if: ${{ success() }}
      run:  npm run build

    # Prepare archive to deploying
    - name: Archive production artifacts
      if: ${{ success() && github.ref == 'refs/heads/itowns_potree' }}
      uses: actions/upload-artifact@v2
      with:
        name: dist-potree
        path: |
          build/**/*.*
          libs/jquery-ui/jquery-ui.min.css
          libs/spectrum/spectrum.css
          libs/jstree/themes/mixed/style.css
          libs/jquery/jquery-3.1.1.min.js
          libs/i18next/i18next.js
          libs/jstree/jstree.min.js
          libs/plasio/js/laslaz.js

  # Deploy on web site
  deploy:
    needs: tests
    if: ${{ github.ref == 'refs/heads/itowns_potree' }}
    runs-on: ubuntu-latest
    name: Deploy to itowns.github.io
    steps:
    # Download artifact from build
    - name: Download bundle
      uses: actions/download-artifact@v2
      with:
        name: dist-potree
    # Copy files for deployment
    - name: build site
      run: |
        mkdir -p itowns/potree/build
        mkdir -p itowns/potree/libs
        cp -R build itowns/potree/
        cp -R libs itowns/potree/

    # Deploy to itowns.github.io
    - name: Deploy to itowns.github.io
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: iTowns/itowns.github.io
        publish_dir: ./itowns/potree
        destination_dir: ./itowns/potree
        publish_branch: master
        enable_jekyll: true
